extraction:
  cpp:
    prepare:
      packages:
        - build-essential
        - automake
        - autoconf
        - libtool
        - pkg-config
        - libssl-dev
    configure:
      command:
        - ./autogen.sh
        - ./configure
